name: firecrest
version: 0.0.1
description: A lightweight, annotation-based http server framework written in Dart
repository: https://github.com/komposten/firecrest

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  collection: ^1.15.0
  meta: ^1.7.0

dev_dependencies: 
  test: ^1.17.12
