name: firecrest
version: 0.0.1
repository: https://github.com/komposten/firecrest
authors:
  - komposten

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  collection: ^1.15.0

dev_dependencies: 
  test: ^1.17.12
